### PR TITLE
Courtney/error component

### LINKED ISSUE #39: Feature: Error component
As the user, when the network request fails to retrieve information from the database, I should see an error message pop so that I know that there is a server error.

Subtasks:

- [x] Create an Error Component that will display if there is an error with the network request. 
- [x] The component should have a Route just like the Page Not Found Component
- [x] When an error occurs the user should be redirected to the Error Component

***See DetailsPage.js and RecModal.js for  
 ```
if (loading) return <p>Loading...</p>
  if (error) navigate("/error") 
```
To find it just command F and input the exact code above. From there you can use this as a basic set up for connecting the Error Component and also use it as a model for all the other components that deal with error handling.

### PR DESCRIPTION
**Pull request by Courtney-Lippman**
- [ ]  Wrote Tests 
- [x] Implemented 
- [ ] Reviewed

## Necessary checkmarks:

- [x] All Tests are Passing in all environments

- [x] The code will run locally

## Type of change

- [x] New feature
- [ ] Bug Fix
- [ ] Refactor
- [x] Styling
- [ ] Testing
- [ ] This change requires a documentation update

## Description of Change:
Issue #39 

This PR adds an Error Component for network request errors. The Error Component navigation was added to Login (for users fetch and the currentUser fetch), Search, and Modal  components. The Error Component was only added to areas that made a network request, this is because apollo caches so it makes for a better UX if the user can see information that was cached.

## Check the correct boxes

- [x]  This broke nothing
- [ ]  This broke some stuff
- [ ]  This broke everything

## Checklist:

- [x]  My code has no unused/commented out code
- [x]  My code follows the style guidelines of this project
- [x]  My code does not generate new warnings
- [x]  I have reviewed my code
- [x]  I have commented my code, particularly in hard-to-understand areas (if applicable)

### CODE REVIEW

File: src/Components/LoginPage/LoginPage.js [hunk 1]
```diff
@@ -33,11 +34,13 @@ const LoginPage = () => {
...
-      variables: { id: signInData.successUserId }
-    })
-    // add error handling here first
-    setUser(data.fetchUser)
+      const { error, loading, data } = await getUser({
+        variables: { id: signInData.successUserId }
+      })
+      if(error) {
+        setErrorState(true)
+      }
```
Comment (sam-rice) [inline src/Components/LoginPage/LoginPage.js:42]: Just a suggestion, but if you don't care about holding the error in state (maybe you do for dev purposes), you can also have:
````
if(error) navigate("/error", { replace: true }) 
`````
here within `loginUser` and skip the extra step of having the conditional on lines 90-93.

File: src/Components/RecModal/RecModal.js [hunk 2]
```diff
@@ -17,8 +18,9 @@ const RecModal = () => {
     const { currentUser } = useContext(UserContext)
     const [sendList, setSendList] = useState([])
     const [allFriendsList, setAllFriendsList] = useState([])
+    const [sentStatus, setSentStatus] = useState('waiting')
     const [createRecommendation] = useMutation(SEND_RECOMMENDATION)
-    const { error, loading, data } = useQuery(GET_ALL_USERS)
+    const { error, loading, data } = useQuery(GET_ALL_USERS, {fetchPolicy: 'network-only'})
```
Comment (sam-rice) [inline src/Components/RecModal/RecModal.js:23]: This is great! Just looked it up in the docs. I wonder if this will come in handy in other situations [🤔](https://emojipedia.org/thinking-face/)

File: src/Components/RecModal/RecModal.js [hunk 3]
```diff
@@ -61,27 +64,83 @@ const RecModal = () => {
...
+            const sendResult = await createRecommendation({ variables: recommendation })
+            if(sendResult.data?.createRecommendation) {
+                setSentStatus('sent')
+                setTimeout(() => {
+                closeModal()}, 1000)
+            }
+        } catch (error) {
+            console.log(error)
+            setSentStatus('failed')
+            setTimeout(() => {
```
Comment (sam-rice) [inline src/Components/RecModal/RecModal.js]: With the way you currently have it, you're passing `setTimeout` an annonymous callback function that invokes `closeModal` (same with lines 77-79). If you're looking to shorten this up/increase readability, you could pass `closeModal` directly as the callback, like this:

````
setTimeout(closeModal, 1500)
````

File: src/Components/RecModal/RecModal.js [hunk 4]
```diff
@@ -61,27 +64,83 @@ const RecModal = () => {
...
-    if (error) navigate("/error") 
+    if (error) {
+      console.log(error)
+      navigate("/error", { replace: true }) 
+    }
+    if(sentStatus === 'waiting') {
+        return(
+            <div className="modalBackground">
+            <div className="modalContainer">
+                <button className='titleCloseBtn' onClick={()=> {
```
Comment (sam-rice) [inline src/Components/RecModal/RecModal.js]: This is similar to the above comment, where if you're looking to slim down the # of lines/increase readability, you could optionally directly pass the `onClick` attribute `closeModal` as a callback.
````
onClick={closeModal}
````

**Review by sam-rice — APPROVED** [review]

File: src/Components/RecModal/RecModal.js (hunk 2 above)
Comment (Courtney-Lippman) [reply src/Components/RecModal/RecModal.js:23]: I think it will! It is a great tool to use in the future!

File: src/Components/LoginPage/LoginPage.js (hunk 1 above)
Comment (Courtney-Lippman) [reply src/Components/LoginPage/LoginPage.js:42]: So I started with exactly what you have above and it actually didn't work. The only way I was able to get the error component to work with the login was to create an errorState and update state. I think it may be due to having multiple queries on one component.

File: src/Components/RecModal/RecModal.js (hunk 3 above)
Comment (Courtney-Lippman) [reply src/Components/RecModal/RecModal.js]: Perfect! I went ahead and changed this! I tried this earlier and it did not work for me but with your example above I realized I tried to invoke the function like this:
setTimeout(closeModal(), 1500)

Thank you for your input here!

File: src/Components/RecModal/RecModal.js (hunk 4 above)
Comment (Courtney-Lippman) [reply src/Components/RecModal/RecModal.js]: Great feed back! I also changed this!

File: src/Components/LoginPage/LoginPage.js (hunk 1 above)
Comment (sam-rice) [reply src/Components/LoginPage/LoginPage.js:42]: Oh, good to know!

**Comment by sam-rice** [comment]
Looks great! Merging now.
